### PR TITLE
Add appendRowRef to allow appending to be triggered elsewhere

### PR DESCRIPTION
**Pull request by pzcfg**
I'd like to be able to trigger the append action from outside of the provided row, but there doesn't currently seem to be an exposed way to do this.

I'm not sure if this is the right way to go about it (I'm hoping there's a cleaner method) but I added an `appendRowRef` prop that gets `appendRow` assigned to it, and I am able to call it from elsewhere.

https://user-images.githubusercontent.com/94077014/151271212-a6450588-4fbb-438b-8485-9bb0c33b9065.mp4

### CODE REVIEW

**Comment by ivoelbert** [comment]
Hi @pzcfg! Thanks for the PR 😄 

The preferred way to add new rows would be to add them in your data source.

If you want the scroll behavior (scroll to the added cell), we're adding support for imperatively scrolling in https://github.com/glideapps/glide-data-grid/pull/147

Is that enough for your use case?

**Comment by pzcfg** [comment]
imperative scrolling would be great! is there also a way to set the selection / focus / etc. so they can start editing/typing in the cell immediately?

**Comment by pzcfg** [comment]
also, would it be possible to get more control over the scrolling? I think `scrollTo` would still be valuable to have, but in some places I want to scroll further down past the cell (even the last cell, using `paddingBottom`) so that there is space for a dropdown from our custom editor

**Comment by ivoelbert** [comment]
> is there also a way to set the selection / focus / etc. so they can start editing/typing in the cell immediately?

Sounds useful! We might add that to the imperative handles. We're also considering adding an imperative handle for adding a cell, so you don't have to replicate all the behavior yourself. We'd so something similar to what you provided, but adding it in `useImperativeHandle` instead of passing down a ref. We'll keep you updated on this.

> would it be possible to get more control over the scrolling? 
Sure! I'm adding that to `scrollTo`. We'll keep you updated on this as well.

**Comment by ivoelbert** [comment]
Just added two optional params, `paddingX` and `paddingY` to `scrollTo`

https://github.com/glideapps/glide-data-grid/pull/150

It'll be available in the next release.

**Comment by ivoelbert** [comment]
Also, I'll close this PR cause in case we implement this (which I think we will), we'll go with a different approach.

**Pull request closed without merging**
