### PR TITLE
Get checkbox alignment working

### PR DESCRIPTION
**Pull request by frankagathos**
@jassmith can you please have a look at this PR

### CODE REVIEW

**Comment by jassmith** [comment]
Kickass will look into shortly

**Review by jassmith — COMMENTED** [review]
This looks like it doesn't attempt to correct the click region? On mobile right now so maybe I missed it?

**Comment by frankagathos** [comment]
@jassmith, I've fixed the hover and click region. Created utils but not sure I moved those under the correct folders.

**Review by jassmith — APPROVED** [review]
This looks awesome, thank you so much for your contribution.

**Pull request merged**
